# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11r82DAbG_-U7nijSuvBy29A5S3ARI0LK
"""

import os
import re
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from torchvision import models

from sklearn.model_selection import train_test_split, GroupShuffleSplit
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)
print("PyTorch:", torch.__version__)

from google.colab import drive
drive.mount("/content/drive")

PROJECT_DIR = "/content/drive/MyDrive/BreakHis_Project"

DATA_DIR = os.path.join(PROJECT_DIR, "data")
OUTPUT_DIR = os.path.join(PROJECT_DIR, "outputs")
METADATA_DIR = os.path.join(PROJECT_DIR, "metadata")
MODEL_DIR = os.path.join(PROJECT_DIR, "models")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(METADATA_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

print("Project folder:", PROJECT_DIR)
print("Data folder:", DATA_DIR)

image_paths = []

for root, dirs, files in os.walk(DATA_DIR):
    for file in files:
        if file.lower().endswith((".png", ".jpg", ".jpeg")):
            image_paths.append(os.path.join(root, file))

print("Total images found:", len(image_paths))

for p in image_paths[:5]:
    print(p)

subtype_map = {
    "A": "adenosis",
    "F": "fibroadenoma",
    "PT": "phyllodes_tumor",
    "TA": "tubular_adenoma",
    "DC": "ductal_carcinoma",
    "LC": "lobular_carcinoma",
    "MC": "mucinous_carcinoma",
    "PC": "papillary_carcinoma"
}

def parse_breakhis_filename(path):
    filename = os.path.basename(path)
    name = os.path.splitext(filename)[0]

    parts = name.split("-")

    if len(parts) < 5:
        return None

    main_part = parts[0]
    patient_id = parts[1] + "-" + parts[2]
    magnification = parts[3]
    image_number = parts[4]

    main_parts = main_part.split("_")

    if len(main_parts) < 3:
        return None

    dataset_prefix = main_parts[0]
    class_code = main_parts[1]
    subtype_code = main_parts[2]

    if class_code == "B":
        label = "benign"
        label_id = 0
    elif class_code == "M":
        label = "malignant"
        label_id = 1
    else:
        return None

    subtype = subtype_map.get(subtype_code, subtype_code)

    return {
        "path": path,
        "filename": filename,
        "dataset_prefix": dataset_prefix,
        "label": label,
        "label_id": label_id,
        "subtype_code": subtype_code,
        "subtype": subtype,
        "patient_id": patient_id,
        "magnification": magnification,
        "image_number": image_number
    }

records = []

for path in image_paths:
    parsed = parse_breakhis_filename(path)
    if parsed is not None:
        records.append(parsed)

df = pd.DataFrame(records)

print("Metadata rows:", len(df))
df.head(10)

metadata_path = os.path.join(METADATA_DIR, "breakhis_metadata.csv")
df.to_csv(metadata_path, index=False)

print("Saved metadata to:", metadata_path)

print("Total images:", len(df))
print("Unique patients/slides:", df["patient_id"].nunique())
print("Labels:")
print(df["label"].value_counts())

print("\nMagnifications:")
print(df["magnification"].value_counts())

print("\nSubtypes:")
print(df["subtype"].value_counts())

plt.figure(figsize=(6,4))
df["label"].value_counts().plot(kind="bar")
plt.title("Image Count by Class")
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "class_distribution.png"))
plt.show()

plt.figure(figsize=(10,5))
df["subtype"].value_counts().plot(kind="bar")
plt.title("Image Count by Tumor Subtype")
plt.xlabel("Tumor Subtype")
plt.ylabel("Number of Images")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "subtype_distribution.png"))
plt.show()

plt.figure(figsize=(6,4))
df["magnification"].value_counts().sort_index().plot(kind="bar")
plt.title("Image Count by Magnification")
plt.xlabel("Magnification")
plt.ylabel("Number of Images")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "magnification_distribution.png"))
plt.show()

pd.crosstab(df["magnification"], df["label"]).plot(kind="bar", figsize=(8,5))
plt.title("Class Distribution by Magnification")
plt.xlabel("Magnification")
plt.ylabel("Number of Images")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "class_by_magnification.png"))
plt.show()

sample_df = df.groupby(["label", "magnification"], group_keys=False).apply(
    lambda x: x.sample(min(len(x), 1), random_state=SEED)
)

sample_df = sample_df.sample(min(len(sample_df), 8), random_state=SEED)

plt.figure(figsize=(14,7))

for i, (_, row) in enumerate(sample_df.iterrows()):
    img = Image.open(row["path"]).convert("RGB")
    plt.subplot(2, 4, i + 1)
    plt.imshow(img)
    plt.title(f"{row['label']} | {row['magnification']}x")
    plt.axis("off")

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "sample_images.png"))
plt.show()

groups = df["patient_id"]

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.30,
    random_state=SEED
)

train_idx, temp_idx = next(splitter.split(df, df["label_id"], groups))

train_df = df.iloc[train_idx].reset_index(drop=True)
temp_df = df.iloc[temp_idx].reset_index(drop=True)

temp_groups = temp_df["patient_id"]

splitter2 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.50,
    random_state=SEED
)

val_idx, test_idx = next(splitter2.split(temp_df, temp_df["label_id"], temp_groups))

val_df = temp_df.iloc[val_idx].reset_index(drop=True)
test_df = temp_df.iloc[test_idx].reset_index(drop=True)

print("Train images:", len(train_df))
print("Validation images:", len(val_df))
print("Test images:", len(test_df))

print("\nTrain patients:", train_df["patient_id"].nunique())
print("Validation patients:", val_df["patient_id"].nunique())
print("Test patients:", test_df["patient_id"].nunique())

print("\nTrain class distribution:")
print(train_df["label"].value_counts())

print("\nValidation class distribution:")
print(val_df["label"].value_counts())

print("\nTest class distribution:")
print(test_df["label"].value_counts())

train_df.to_csv(os.path.join(METADATA_DIR, "train_metadata.csv"), index=False)
val_df.to_csv(os.path.join(METADATA_DIR, "val_metadata.csv"), index=False)
test_df.to_csv(os.path.join(METADATA_DIR, "test_metadata.csv"), index=False)

print("Split metadata saved.")

class BreakHisDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        row = self.dataframe.iloc[index]

        image = Image.open(row["path"]).convert("RGB")
        label = int(row["label_id"])

        if self.transform:
            image = self.transform(image)

        return image, label

IMG_SIZE = 224
BATCH_SIZE = 32

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

train_dataset = BreakHisDataset(train_df, transform=train_transform)
val_dataset = BreakHisDataset(val_df, transform=eval_transform)
test_dataset = BreakHisDataset(test_df, transform=eval_transform)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

print("DataLoaders ready.")

model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.DEFAULT)

num_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_features, 2)

model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

print(model.classifier)

def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()

    running_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in tqdm(dataloader):
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = accuracy_score(all_labels, all_preds)

    return epoch_loss, epoch_acc


def evaluate(model, dataloader, criterion, device):
    model.eval()

    running_loss = 0.0
    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for images, labels in tqdm(dataloader):
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            probs = torch.softmax(outputs, dim=1)[:, 1]
            preds = torch.argmax(outputs, dim=1)

            running_loss += loss.item()

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = accuracy_score(all_labels, all_preds)

    return epoch_loss, epoch_acc, all_labels, all_preds, all_probs

EPOCHS = 5

best_val_acc = 0.0
best_model_path = os.path.join(MODEL_DIR, "best_mobilenetv2_breakhis.pth")

history = {
    "train_loss": [],
    "train_acc": [],
    "val_loss": [],
    "val_acc": []
}

for epoch in range(EPOCHS):
    print(f"\nEpoch {epoch + 1}/{EPOCHS}")

    train_loss, train_acc = train_one_epoch(
        model,
        train_loader,
        criterion,
        optimizer,
        device
    )

    val_loss, val_acc, _, _, _ = evaluate(
        model,
        val_loader,
        criterion,
        device
    )

    history["train_loss"].append(train_loss)
    history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)

    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val Loss:   {val_loss:.4f} | Val Acc:   {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), best_model_path)
        print("Best model saved.")

print("\nTraining complete.")
print("Best validation accuracy:", best_val_acc)

plt.figure(figsize=(7,5))
plt.plot(history["train_loss"], label="Train Loss")
plt.plot(history["val_loss"], label="Validation Loss")
plt.title("Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "loss_curve.png"))
plt.show()

plt.figure(figsize=(7,5))
plt.plot(history["train_acc"], label="Train Accuracy")
plt.plot(history["val_acc"], label="Validation Accuracy")
plt.title("Training and Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "accuracy_curve.png"))
plt.show()

model.load_state_dict(torch.load(best_model_path, map_location=device))
model = model.to(device)

test_loss, test_acc, y_true, y_pred, y_prob = evaluate(
    model,
    test_loader,
    criterion,
    device
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

target_names = ["benign", "malignant"]

report = classification_report(
    y_true,
    y_pred,
    target_names=target_names
)

print(report)

report_path = os.path.join(OUTPUT_DIR, "classification_report.txt")

with open(report_path, "w") as f:
    f.write(report)

print("Saved report to:", report_path)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

try:
    roc_auc = roc_auc_score(y_true, y_prob)
except:
    roc_auc = None

metrics = {
    "accuracy": accuracy,
    "precision": precision,
    "recall": recall,
    "f1_score": f1,
    "roc_auc": roc_auc
}

metrics_df = pd.DataFrame([metrics])
metrics_df

metrics_df.to_csv(os.path.join(OUTPUT_DIR, "test_metrics.csv"), index=False)
print("Metrics saved.")

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()

plt.xticks([0, 1], ["benign", "malignant"])
plt.yticks([0, 1], ["benign", "malignant"])

plt.xlabel("Predicted Label")
plt.ylabel("True Label")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix.png"))
plt.show()

test_results = test_df.copy()
test_results["true_label"] = y_true
test_results["predicted_label"] = y_pred
test_results["prob_malignant"] = y_prob

misclassified = test_results[test_results["true_label"] != test_results["predicted_label"]]

print("Misclassified images:", len(misclassified))
misclassified.head()

num_images = min(8, len(misclassified))

if num_images > 0:
    sample_misclassified = misclassified.sample(num_images, random_state=SEED)

    plt.figure(figsize=(14,7))

    for i, (_, row) in enumerate(sample_misclassified.iterrows()):
        img = Image.open(row["path"]).convert("RGB")

        true_name = "malignant" if row["true_label"] == 1 else "benign"
        pred_name = "malignant" if row["predicted_label"] == 1 else "benign"

        plt.subplot(2, 4, i + 1)
        plt.imshow(img)
        plt.title(f"True: {true_name}\nPred: {pred_name}")
        plt.axis("off")

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "misclassified_images.png"))
    plt.show()
else:
    print("No misclassified images found.")

test_results["correct"] = test_results["true_label"] == test_results["predicted_label"]

magnification_performance = test_results.groupby("magnification")["correct"].mean().reset_index()
magnification_performance.columns = ["magnification", "accuracy"]

magnification_performance

plt.figure(figsize=(6,4))
plt.bar(magnification_performance["magnification"], magnification_performance["accuracy"])
plt.title("Accuracy by Magnification")
plt.xlabel("Magnification")
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "accuracy_by_magnification.png"))
plt.show()

test_results_path = os.path.join(OUTPUT_DIR, "test_predictions.csv")
test_results.to_csv(test_results_path, index=False)

print("Saved test predictions to:", test_results_path)

print("===== FINAL SUMMARY =====")
print("Total images:", len(df))
print("Unique patients/slides:", df["patient_id"].nunique())
print("Train images:", len(train_df))
print("Validation images:", len(val_df))
print("Test images:", len(test_df))
print("Test accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("ROC-AUC:", roc_auc)
print("=========================")